"""initial schema

Revision ID: aebf81166c6e
Revises: 
Create Date: 2026-09-13 23:48:34.601532
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'aebf81166c6e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_defs',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_badge_defs'))
    )
    op.create_table('event_defs',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('min_week', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_event_defs'))
    )
    op.create_table('players',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('weekly_income', sa.Integer(), nullable=False),
    sa.Column('free_coins', sa.Integer(), nullable=False),
    sa.Column('sound_on', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('free_coins >= 0', name=op.f('ck_players_free_coins_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_device_id'), 'players', ['device_id'], unique=True)
    op.create_table('shop_items',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'WATER', 'PLAY', 'SAVE', name='category', native_enum=False, length=24), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('old_cost', sa.Integer(), nullable=True),
    sa.Column('glyph', sa.String(length=20), nullable=False),
    sa.Column('restore', sa.Integer(), nullable=False),
    sa.Column('xp_bonus', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_shop_items'))
    )
    op.create_table('task_defs',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('LESSON', 'WEEK', 'HABIT', 'DAY', name='taskkind', native_enum=False, length=24), nullable=False),
    sa.Column('target', sa.Enum('QUIZ', 'PLAN', 'GOAL', 'SHOP', name='tasktarget', native_enum=False, length=24), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_task_defs'))
    )
    op.create_table('goals',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_goals_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_player_id'), 'goals', ['player_id'], unique=False)
    op.create_table('pets',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('species', sa.Enum('FINIK', 'CACTUS', 'SPARK', name='species', native_enum=False, length=24), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('need_food', sa.Integer(), nullable=False),
    sa.Column('need_water', sa.Integer(), nullable=False),
    sa.Column('need_play', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_pets_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets')),
    sa.UniqueConstraint('player_id', name=op.f('uq_pets_player_id'))
    )
    op.create_table('player_badges',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('badge_slug', sa.String(length=40), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_slug'], ['badge_defs.slug'], name=op.f('fk_player_badges_badge_slug_badge_defs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_badges_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'badge_slug', name=op.f('pk_player_badges'))
    )
    op.create_table('quiz_questions',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('lesson_slug', sa.String(length=40), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('right_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_slug'], ['task_defs.slug'], name=op.f('fk_quiz_questions_lesson_slug_task_defs')),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_quiz_questions'))
    )
    op.create_index(op.f('ix_quiz_questions_lesson_slug'), 'quiz_questions', ['lesson_slug'], unique=False)
    op.create_table('weeks',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('overrun', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_weeks_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weeks')),
    sa.UniqueConstraint('player_id', 'number', name='uq_weeks_player_number')
    )
    op.create_index(op.f('ix_weeks_player_id'), 'weeks', ['player_id'], unique=False)
    op.create_table('action_log',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('CARE', 'PURCHASE', 'DEPOSIT', 'OVERRUN', 'TASK_REWARD', 'EVENT_CHOICE', 'DAY_END', 'WEEK_CLOSE', 'PARENT_BONUS', name='actionkind', native_enum=False, length=24), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'WATER', 'PLAY', 'SAVE', name='category', native_enum=False, length=24), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_action_log_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_action_log_week_id_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log'))
    )
    op.create_index(op.f('ix_action_log_player_id'), 'action_log', ['player_id'], unique=False)
    op.create_index(op.f('ix_action_log_week_id'), 'action_log', ['week_id'], unique=False)
    op.create_table('event_instances',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('event_slug', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('chosen', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_slug'], ['event_defs.slug'], name=op.f('fk_event_instances_event_slug_event_defs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_event_instances_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_event_instances_week_id_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_instances'))
    )
    op.create_index(op.f('ix_event_instances_player_id'), 'event_instances', ['player_id'], unique=False)
    op.create_table('plan_entries',
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'WATER', 'PLAY', 'SAVE', name='category', native_enum=False, length=24), nullable=False),
    sa.Column('planned', sa.Integer(), nullable=False),
    sa.Column('spent', sa.Integer(), nullable=False),
    sa.CheckConstraint('planned >= 0 AND spent >= 0', name=op.f('ck_plan_entries_amounts_non_negative')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_plan_entries_week_id_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('week_id', 'category', name=op.f('pk_plan_entries'))
    )
    op.create_table('purchases',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('item_slug', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_slug'], ['shop_items.slug'], name=op.f('fk_purchases_item_slug_shop_items')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_purchases_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_purchases_week_id_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    op.create_index(op.f('ix_purchases_player_id'), 'purchases', ['player_id'], unique=False)
    op.create_table('task_progress',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('task_slug', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_task_progress_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_slug'], ['task_defs.slug'], name=op.f('fk_task_progress_task_slug_task_defs')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_task_progress_week_id_weeks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_progress')),
    sa.UniqueConstraint('player_id', 'week_id', 'task_slug', name='uq_task_progress_week')
    )
    op.create_index(op.f('ix_task_progress_player_id'), 'task_progress', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_progress_player_id'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_index(op.f('ix_purchases_player_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('plan_entries')
    op.drop_index(op.f('ix_event_instances_player_id'), table_name='event_instances')
    op.drop_table('event_instances')
    op.drop_index(op.f('ix_action_log_week_id'), table_name='action_log')
    op.drop_index(op.f('ix_action_log_player_id'), table_name='action_log')
    op.drop_table('action_log')
    op.drop_index(op.f('ix_weeks_player_id'), table_name='weeks')
    op.drop_table('weeks')
    op.drop_index(op.f('ix_quiz_questions_lesson_slug'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_table('player_badges')
    op.drop_table('pets')
    op.drop_index(op.f('ix_goals_player_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_table('task_defs')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_players_device_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('event_defs')
    op.drop_table('badge_defs')
    # ### end Alembic commands ###
