"""прогресс заданий: данные и награда

Revision ID: 56aa5329afea
Revises: aebf81166c6e
Create Date: 2026-09-13 23:59:36.965714
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '56aa5329afea'
down_revision: str | None = 'aebf81166c6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_progress', sa.Column('data', sa.JSON(), nullable=False))
    op.add_column('task_progress', sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_progress', 'rewarded_at')
    op.drop_column('task_progress', 'data')
    # ### end Alembic commands ###
