"""Справочный контент. Числа и тексты повторяют SampleData мобильного клиента."""

SHOP_ITEMS = [
    dict(
        slug="water_3d",
        name="Вода, 3 дня",
        category="WATER",
        cost=3,
        old_cost=None,
        glyph="CIRCLE",
        restore=45,
        xp_bonus=0,
        hidden=False,
        slot="",
    ),
    dict(
        slug="vitamins",
        name="Витамины",
        category="FOOD",
        cost=6,
        old_cost=10,
        glyph="ROUNDED",
        restore=20,
        xp_bonus=2,
        hidden=False,
        slot="",
    ),
    dict(
        slug="food_week",
        name="Корм на неделю",
        category="FOOD",
        cost=12,
        old_cost=None,
        glyph="POT",
        restore=100,
        xp_bonus=0,
        hidden=False,
        slot="",
    ),
    dict(
        slug="ball",
        name="Мячик",
        category="PLAY",
        cost=3,
        old_cost=5,
        glyph="CIRCLE",
        restore=25,
        xp_bonus=0,
        hidden=False,
        slot="",
    ),
    dict(
        slug="new_pot",
        name="Уютное гнездо",
        category="PLAY",
        cost=18,
        old_cost=None,
        glyph="TALL_POT",
        restore=0,
        xp_bonus=10,
        hidden=False,
        slot="pot",
    ),
    dict(
        slug="pot_blue",
        name="Синяя подушка",
        category="PLAY",
        cost=3,
        old_cost=None,
        glyph="POT",
        restore=0,
        xp_bonus=2,
        hidden=False,
        slot="pot",
    ),
    dict(
        slug="pot_striped",
        name="Полосатая подушка",
        category="PLAY",
        cost=4,
        old_cost=None,
        glyph="TALL_POT",
        restore=0,
        xp_bonus=3,
        hidden=False,
        slot="pot",
    ),
    dict(
        slug="watering_can",
        name="Удобная поилка",
        category="WATER",
        cost=8,
        old_cost=11,
        glyph="BUCKET",
        restore=20,
        xp_bonus=5,
        hidden=False,
        slot="",
    ),
    dict(
        slug="berry_treat",
        name="Ягодный корм",
        category="FOOD",
        cost=4,
        old_cost=None,
        glyph="ROUNDED",
        restore=35,
        xp_bonus=1,
        hidden=True,
        slot="",
    ),
    dict(
        slug="leaf_soap",
        name="Средство для перьев",
        category="FOOD",
        cost=5,
        old_cost=None,
        glyph="ROUNDED",
        restore=15,
        xp_bonus=0,
        hidden=False,
        slot="",
    ),
    dict(
        slug="ribbon",
        name="Ленточка",
        category="PLAY",
        cost=4,
        old_cost=None,
        glyph="CIRCLE",
        restore=0,
        xp_bonus=4,
        hidden=False,
        slot="accessory",
    ),
    dict(
        slug="hat_leaf",
        name="Шляпа для совы",
        category="PLAY",
        cost=3,
        old_cost=None,
        glyph="ROUNDED",
        restore=0,
        xp_bonus=2,
        hidden=False,
        slot="accessory",
    ),
    dict(
        slug="glasses_round",
        name="Медаль исследователя",
        category="PLAY",
        cost=3,
        old_cost=None,
        glyph="CIRCLE",
        restore=0,
        xp_bonus=2,
        hidden=False,
        slot="accessory",
    ),
    dict(
        slug="scarf_knit",
        name="Бандана",
        category="PLAY",
        cost=2,
        old_cost=None,
        glyph="ROUNDED",
        restore=0,
        xp_bonus=1,
        hidden=False,
        slot="accessory",
    ),
    dict(
        slug="charm_can",
        name="Рюкзак",
        category="PLAY",
        cost=3,
        old_cost=None,
        glyph="BUCKET",
        restore=0,
        xp_bonus=2,
        hidden=False,
        slot="accessory",
    ),
    dict(
        slug="sun_sticker",
        name="Украшение гнезда",
        category="PLAY",
        cost=2,
        old_cost=None,
        glyph="CIRCLE",
        restore=0,
        xp_bonus=2,
        hidden=False,
        slot="accessory",
    ),
]

TASK_DEFS = [
    dict(
        slug="adventure_market",
        title="Экспедиция: ярмарка",
        kind="LESSON",
        target="QUIZ",
        reward=14,
        params={"adventure": True},
    ),
    dict(
        slug="adventure_storm",
        title="Экспедиция: шторм",
        kind="LESSON",
        target="QUIZ",
        reward=14,
        params={"adventure": True},
    ),
    dict(
        slug="adventure_dream",
        title="Экспедиция: большое окно",
        kind="LESSON",
        target="QUIZ",
        reward=16,
        params={"adventure": True},
    ),
    dict(
        slug="lesson_discount",
        title="Игра: касса и скидка",
        kind="LESSON",
        target="QUIZ",
        reward=6,
        params={},
    ),
    dict(
        slug="save_10",
        title="Отложи 10 монет до конца недели",
        kind="WEEK",
        target="GOAL",
        reward=8,
        params={"amount": 10},
    ),
    dict(
        slug="food_plan",
        title="Уложись в план по еде",
        kind="WEEK",
        target="PLAN",
        reward=10,
        params={"category": "FOOD"},
    ),
    dict(
        slug="streak_7",
        title="Позаботься о сове 7 дней",
        kind="HABIT",
        target=None,
        reward=5,
        params={"days": 7},
    ),
    dict(
        slug="buy_sale",
        title="Купи что-то со скидкой",
        kind="DAY",
        target="SHOP",
        reward=4,
        params={"count": 1},
    ),
    dict(
        slug="buy_need",
        title="Купи обязательное: еду или воду",
        kind="DAY",
        target="SHOP",
        reward=5,
        params={"count": 1, "need": True},
    ),
    dict(
        slug="lesson_need_want",
        title="Игра: нужно или хочется",
        kind="LESSON",
        target="QUIZ",
        reward=6,
        params={},
    ),
    dict(
        slug="lesson_budget",
        title="Игра: собери бюджет",
        kind="LESSON",
        target="QUIZ",
        reward=8,
        params={},
    ),
    dict(
        slug="lesson_saving",
        title="Игра: путь к мечте",
        kind="LESSON",
        target="QUIZ",
        reward=8,
        params={},
    ),
    dict(
        slug="lesson_compare",
        title="Игра: охота за честной ценой",
        kind="LESSON",
        target="QUIZ",
        reward=9,
        params={},
    ),
    dict(
        slug="lesson_earn",
        title="Игра: первая мастерская",
        kind="LESSON",
        target="QUIZ",
        reward=9,
        params={},
    ),
    dict(
        slug="lesson_debt",
        title="Игра: ловушка долга",
        kind="LESSON",
        target="QUIZ",
        reward=9,
        params={},
    ),
]

QUIZ_QUESTIONS = [
    dict(
        slug="q_discount_1",
        lesson_slug="lesson_discount",
        order=1,
        question="Корм стоит 10, скидка 40%. Сколько заплатишь?",
        options=["4 монеты", "6 монет", "8 монет"],
        right_index=1,
        explanation="40% от 10 — это 4. Значит платишь 10 − 4 = 6.",
    ),
    dict(
        slug="q_discount_2",
        lesson_slug="lesson_discount",
        order=2,
        question="Доход 40 монет. Сколько это 20% в копилку?",
        options=["4 монеты", "8 монет", "20 монет"],
        right_index=1,
        explanation="20% — это пятая часть: 40 ÷ 5 = 8.",
    ),
    dict(
        slug="q_discount_3",
        lesson_slug="lesson_discount",
        order=3,
        question="В плане на еду 14, потратил 18. Что произошло?",
        options=["Перерасход на 4", "Сэкономил 4", "Ничего"],
        right_index=0,
        explanation="Лишние 4 монеты придётся взять из другой статьи — чаще всего из копилки.",
    ),
    dict(
        slug="q_need_1",
        lesson_slug="lesson_need_want",
        order=1,
        question="Куда положишь корм для совы?",
        options=["Нужно", "Хочется"],
        right_index=0,
        explanation="Корм нужен сове каждый день. Сначала заботимся о важном.",
    ),
    dict(
        slug="q_need_2",
        lesson_slug="lesson_need_want",
        order=2,
        question="Куда положишь мячик?",
        options=["Нужно", "Хочется"],
        right_index=1,
        explanation="Мячик радует, но покупку можно отложить, если монет мало.",
    ),
    dict(
        slug="q_need_3",
        lesson_slug="lesson_need_want",
        order=3,
        question="Монеты в копилку — это какое решение?",
        options=["Потратить на желаемое", "Отложить, чтобы накопить", "Купить всё сразу"],
        right_index=1,
        explanation="Отложить — значит накопить на мечту. Эти монеты не тратят на игрушки.",
    ),
    dict(
        slug="q_budget_1",
        lesson_slug="lesson_budget",
        order=1,
        question="У тебя 12 монет. На еду нужно 6, на воду 3. Сколько останется?",
        options=["3 монеты", "6 монет", "9 монет"],
        right_index=0,
        explanation="Сначала важное: 12 - 6 - 3 = 3 монеты на остальное.",
    ),
    dict(
        slug="q_budget_2",
        lesson_slug="lesson_budget",
        order=2,
        question="На игру выделено 4 монеты, потрачено 3. Сколько осталось?",
        options=["1 монета", "3 монеты", "7 монет"],
        right_index=0,
        explanation="В статье игры осталось 4 - 3 = 1 монета.",
    ),
    dict(
        slug="q_budget_3",
        lesson_slug="lesson_budget",
        order=3,
        question="Вода закончилась, а в лавке появился новый мяч. Что купишь сначала?",
        options=["Воду", "Мяч", "Всё сразу"],
        right_index=0,
        explanation="Вода нужна сове. Мяч можно купить позже, если останутся монеты.",
    ),
    dict(
        slug="q_save_1",
        lesson_slug="lesson_saving",
        order=1,
        question="Мечта стоит 20 монет. В копилке уже 8. Сколько ещё нужно?",
        options=["12 монет", "8 монет", "28 монет"],
        right_index=0,
        explanation="20 - 8 = 12. Столько осталось собрать до мечты.",
    ),
    dict(
        slug="q_save_2",
        lesson_slug="lesson_saving",
        order=2,
        question="Откладываешь по 2 монеты в неделю. Когда накопишь 6?",
        options=["Через 3 недели", "Через 2 недели", "Через 6 недель"],
        right_index=0,
        explanation="2 + 2 + 2 = 6, значит понадобится три недели.",
    ),
    dict(
        slug="q_save_3",
        lesson_slug="lesson_saving",
        order=3,
        question="Осталось 4 свободные монеты. Что приблизит мечту?",
        options=["Отложить 4", "Купить наклейку", "Потратить всё"],
        right_index=0,
        explanation="Если отложить 4 монеты, до мечты останется меньше шагов.",
    ),
    dict(
        slug="q_compare_1",
        lesson_slug="lesson_compare",
        order=1,
        question="Три семечка стоят 6 монет, а пять семечек - 8. Где одно дешевле?",
        options=["Набор из трёх", "Набор из пяти"],
        right_index=1,
        explanation=(
            "В первом наборе семечко стоит 2 монеты. Пять таких стоили бы 10, "
            "но второй набор стоит 8. Он выгоднее, если все семена нужны."
        ),
    ),
    dict(
        slug="q_compare_2",
        lesson_slug="lesson_compare",
        order=2,
        question="Вода на два дня стоит 4 монеты. Сколько стоит один день?",
        options=["1 монета", "2 монеты", "4 монеты"],
        right_index=1,
        explanation="Раздели цену на количество дней: 4 / 2 = 2 монеты за день.",
    ),
    dict(
        slug="q_compare_3",
        lesson_slug="lesson_compare",
        order=3,
        question="Нужная лейка стоит 12 монет. Скидка 50%. Сколько заплатишь?",
        options=["4 монеты", "6 монет", "12 монет"],
        right_index=1,
        explanation="Половина от 12 - 6. Проверь цену после скидки, а не только яркий ярлык.",
    ),
    dict(
        slug="q_earn_1",
        lesson_slug="lesson_earn",
        order=1,
        question="За помощь с растениями платят 12 монет. На материалы ушло 3. Сколько заработал?",
        options=["3 монеты", "9 монет", "12 монет"],
        right_index=1,
        explanation="Настоящий заработок - доход минус расходы: 12 - 3 = 9 монет.",
    ),
    dict(
        slug="q_earn_2",
        lesson_slug="lesson_earn",
        order=2,
        question="Сосед предлагает работу. Что стоит сделать до начала?",
        options=[
            "Согласовать со взрослым и уточнить оплату",
            "Поверить любому обещанию",
            "Отдать пароль",
        ],
        right_index=0,
        explanation="Работу и оплату сначала обсуди со взрослым. Пароли никому не сообщают.",
    ),
    dict(
        slug="q_earn_3",
        lesson_slug="lesson_earn",
        order=3,
        question="Из 9 заработанных монет 4 идут на мечту и 3 на еду. Сколько осталось?",
        options=["2 монеты", "4 монеты", "6 монет"],
        right_index=0,
        explanation="9 - 4 - 3 = 2. Заработок тоже полезно распределять по плану.",
    ),
    dict(
        slug="q_debt_1",
        lesson_slug="lesson_debt",
        order=1,
        question="Взял 8 монет, а вернуть нужно 10. Сколько лишних монет отдашь?",
        options=["2 монеты", "8 монет", "10 монет"],
        right_index=0,
        explanation="10 - 8 = 2 монеты переплаты. Долг может сделать вещь дороже.",
    ),
    dict(
        slug="q_debt_2",
        lesson_slug="lesson_debt",
        order=2,
        question="Игра стоит 10 монет, а у тебя 4. Какой план безопаснее?",
        options=["Копить и сравнить цены", "Занять у незнакомца", "Взять код карты взрослого"],
        right_index=0,
        explanation=(
            "Желание можно отложить. Не бери долг и не пользуйся чужими платёжными данными."
        ),
    ),
    dict(
        slug="q_debt_3",
        lesson_slug="lesson_debt",
        order=3,
        question="Тебе обещают вещь сейчас, если потом отдашь 15 вместо 10. Что спросить?",
        options=["Сколько составит переплата", "Какой цвет упаковки", "Когда откроется лавка"],
        right_index=0,
        explanation="Разница 5 монет - цена такого обещания. Сначала узнай полную стоимость.",
    ),
]

# Presentation only. Correct answers remain in quiz_questions and never leave the server.
QUESTION_ACTIVITY = {
    "q_discount_1": ("COINS", "Касса со скидкой"),
    "q_discount_2": ("COINS", "Пополняем копилку"),
    "q_discount_3": ("CHOICE", "План и покупки"),
    "q_need_1": ("SORT", "Корм для совы"),
    "q_need_2": ("SORT", "Мячик для игры"),
    "q_need_3": ("CHOICE", "Свободные монеты"),
    "q_budget_1": ("COINS", "Собери остаток"),
    "q_budget_2": ("COINS", "Монеты на игру"),
    "q_budget_3": ("CHOICE", "Что важнее сейчас?"),
    "q_save_1": ("COINS", "Сколько до мечты?"),
    "q_save_2": ("CHOICE", "Шаги по неделям"),
    "q_save_3": ("CHOICE", "Выбор для мечты"),
    "q_compare_1": ("CHOICE", "Два набора семян"),
    "q_compare_2": ("COINS", "Цена одного дня"),
    "q_compare_3": ("COINS", "Ценник со скидкой"),
    "q_earn_1": ("COINS", "Заработок мастерской"),
    "q_earn_2": ("CHOICE", "Сначала договоримся"),
    "q_earn_3": ("COINS", "Разложи заработок"),
    "q_debt_1": ("COINS", "Цена долга"),
    "q_debt_2": ("CHOICE", "План для покупки"),
    "q_debt_3": ("CHOICE", "Скрытая переплата"),
}

BADGE_DEFS = [
    dict(
        slug="plan_kept",
        name="План выполнен",
        note="Уложиться в план 4 недели подряд",
        params={"weeks": 4},
    ),
    dict(
        slug="twenty_percent",
        name="Двадцать процентов",
        note="Держать копилку ≥20% месяц",
        params={"weeks": 4, "percent": 20},
    ),
    dict(
        slug="sale_hunter",
        name="Охотник за скидками",
        note="10 покупок со скидкой",
        params={"count": 10},
    ),
    dict(slug="halfway", name="Полпути", note="Половина цели собрана", params={"percent": 50}),
    dict(slug="no_debt", name="Без долгов", note="Неделя без перерасхода", params={"weeks": 1}),
    dict(
        slug="big_tree",
        name="Большое дерево",
        note="Вырастить Финика до дерева",
        params={"stage": 4},
    ),
]

# Варианты: coins, pay (свободные или копилка), cost, need, xp, note,
# price_delta, sale_percent, vaccinate (недель защиты), unlock_shop.
EVENT_DEFS = [
    dict(
        slug="sale_day",
        title="Распродажа в лавке",
        weight=3,
        min_week=1,
        text=("Сегодня в лавке скидки до 40%. Хороший момент запастись нужным, если оно в плане."),
        options=[
            dict(
                key="look",
                label="Заглянуть в лавку",
                effects={
                    "sale_percent": 10,
                    "note": "В лавке сегодня дешевле до 10%. Скидка до конца этой недели.",
                },
            ),
            dict(key="skip", label="Пройти мимо", effects={"xp": 2}),
        ],
    ),
    dict(
        slug="price_rise",
        title="Корм подорожал",
        weight=2,
        min_week=2,
        text="Поставщик поднял цены: корм на этой неделе стоит на 2 монеты дороже.",
        options=[
            dict(
                key="ok",
                label="Понятно, буду внимательнее",
                effects={
                    "price_delta": {"FOOD": 2},
                    "note": "Корм в лавке дороже на 2 монеты до конца недели.",
                },
            ),
        ],
    ),
    dict(
        slug="sick",
        title="Сова приболела",
        weight=2,
        min_week=1,
        text=(
            "Крылья опустились. Витамины поправят дело, "
            "но можно и подождать: само пройдёт за пару дней."
        ),
        options=[
            dict(
                key="treat",
                label="Купить витамины за 6",
                effects={"cost": {"FOOD": 6}, "need": {"FOOD": 30}},
            ),
            dict(key="wait", label="Подождать", effects={"need": {"FOOD": -20, "PLAY": -10}}),
        ],
    ),
    dict(
        slug="scam_message",
        title="Странное сообщение",
        weight=2,
        min_week=1,
        text="«Переведи 10 монет и получишь 30 обратно!» Пишет кто-то незнакомый.",
        options=[
            dict(
                key="pay",
                label="Перевести 10 монет",
                effects={
                    "coins": -10,
                    "xp": -5,
                    "note": (
                        "Монеты пропали. Так работают мошенники: обещают много, а забирают твоё."
                    ),
                },
            ),
            dict(
                key="ignore",
                label="Не отвечать",
                effects={
                    "xp": 5,
                    "coins": 2,
                    "note": "Верно. Незнакомцы, которые обещают удвоить монеты, всегда обманывают.",
                },
            ),
        ],
    ),
    dict(
        slug="charity",
        title="Соседский питомец заболел",
        weight=1,
        min_week=2,
        text="Соседям не хватает 3 монет на витамины для их совы.",
        options=[
            dict(
                key="help",
                label="Помочь 3 монетами",
                effects={"coins": -3, "need": {"PLAY": 15}, "xp": 3},
            ),
            dict(key="decline", label="Сейчас не могу", effects={}),
        ],
    ),
    dict(
        slug="crisis",
        title="Неожиданный расход",
        weight=2,
        min_week=2,
        text="Поилка треснула: срочно нужно 5 монет на замену, иначе вода будет утекать.",
        options=[
            dict(
                key="pay",
                label="Заплатить 5",
                effects={
                    "pay": 5,
                    "xp": 2,
                    "note": "Поилку заменили. Неприятно, зато питомец в безопасности.",
                },
            ),
            dict(
                key="skip",
                label="Подождать",
                effects={
                    "need": {"WATER": -15, "FOOD": -10},
                    "xp": -3,
                    "note": "Без заплаты день вышел тяжёлым. Иногда расход нельзя откладывать.",
                },
            ),
        ],
    ),
    dict(
        slug="new_food",
        title="Новый корм в лавке",
        weight=1,
        min_week=1,
        text="Привезли ягодный корм: вкусный, недорогой. Можно взять сразу или оставить в лавке.",
        options=[
            dict(
                key="buy",
                label="Купить сейчас за 4 из еды",
                effects={
                    "cost": {"FOOD": 4},
                    "need": {"FOOD": 35},
                    "unlock_shop": "berry_treat",
                    "xp": 1,
                    "note": "Ягодный корм куплен и теперь будет в лавке.",
                },
            ),
            dict(
                key="later",
                label="Пусть стоит в лавке",
                effects={
                    "unlock_shop": "berry_treat",
                    "note": "Ягодный корм появился на витрине. Купишь, когда будет в плане.",
                },
            ),
            dict(key="skip", label="Не сейчас", effects={}),
        ],
    ),
    dict(
        slug="guests",
        title="Пришли гости",
        weight=2,
        min_week=1,
        text="Соседские совы в гостях. Можно потратить 3 из игр на угощение — или отказаться.",
        options=[
            dict(
                key="host",
                label="Угостить за 3 из игр",
                effects={
                    "cost": {"PLAY": 3},
                    "need": {"PLAY": 15},
                    "xp": 2,
                    "note": "Гостям было весело. Игры похудели, настроение выросло.",
                },
            ),
            dict(
                key="skip",
                label="Не в этот раз",
                effects={
                    "need": {"PLAY": -10},
                    "xp": -1,
                    "note": "Гости ушли. Немного скучно, зато монеты на месте.",
                },
            ),
        ],
    ),
    dict(
        slug="vaccine",
        title="Прививка для совы",
        weight=2,
        min_week=1,
        text="Можно заплатить 3 монеты сейчас — и болезнь на ближайшие недели не придёт.",
        options=[
            dict(
                key="pay",
                label="Привить за 3",
                effects={
                    "pay": 3,
                    "vaccinate": 4,
                    "xp": 2,
                    "note": "Прививка сделана. Событие болезни не придёт ещё несколько недель.",
                },
            ),
            dict(
                key="skip",
                label="Потом",
                effects={
                    "note": "Без прививки питомец может приболеть в другой день. Это твой выбор.",
                },
            ),
        ],
    ),
    dict(
        slug="pyramid",
        title="Пирамида «вернём втрое»",
        weight=2,
        min_week=2,
        text="«Вложи 8 монет — через неделю вернём 20!» Это не копилка, а пирамида.",
        options=[
            dict(
                key="invest",
                label="Вложить 8 монет",
                effects={
                    "coins": -8,
                    "xp": -5,
                    "need": {"PLAY": -10},
                    "note": (
                        "Монеты пропали. Пирамида обещает много, а забирает твоё. "
                        "Через неделю 20 не придут — так и задумано мошенниками."
                    ),
                },
            ),
            dict(
                key="refuse",
                label="Не вкладывать",
                effects={
                    "xp": 5,
                    "coins": 2,
                    "note": "Верно. Кто обещает вернуть втрое через неделю, забирает монеты.",
                },
            ),
        ],
    ),
]
