"""Порты: что приложению нужно от хранилища. Реализации живут в infrastructure."""

from typing import Protocol, Self
from uuid import UUID

from domain.entities import (
    Badge,
    EventDef,
    EventInstance,
    Goal,
    LogEntry,
    Pet,
    Player,
    Purchase,
    QuizQuestion,
    ShopItem,
    TaskDef,
    TaskProgress,
    Week,
)
from domain.enums import ActionKind


class PlayerRepository(Protocol):
    async def get(self, player_id: UUID) -> Player | None: ...
    async def get_by_device(self, device_id: str) -> Player | None: ...
    async def add(self, player: Player) -> None: ...
    async def save(self, player: Player) -> None: ...
    async def wipe_progress(self, player_id: UUID) -> None: ...


class PetRepository(Protocol):
    async def get_by_player(self, player_id: UUID) -> Pet | None: ...
    async def add(self, pet: Pet) -> None: ...
    async def save(self, pet: Pet) -> None: ...


class WeekRepository(Protocol):
    async def get_current(self, player_id: UUID) -> Week | None: ...
    async def list_closed(self, player_id: UUID, limit: int) -> list[Week]: ...
    async def add(self, week: Week) -> None: ...
    async def save(self, week: Week) -> None: ...


class GoalRepository(Protocol):
    async def get_active(self, player_id: UUID) -> Goal | None: ...
    async def add(self, goal: Goal) -> None: ...
    async def save(self, goal: Goal) -> None: ...


class LogRepository(Protocol):
    async def add(self, entry: LogEntry) -> None: ...
    async def care_days(self, player_id: UUID, week_id: UUID) -> int: ...
    async def sum_amount(self, player_id: UUID, week_id: UUID, kind: ActionKind) -> int: ...
    async def list_day(self, player_id: UUID, week_id: UUID, day: int) -> list[LogEntry]: ...
    async def latest(self, player_id: UUID, kind: ActionKind) -> LogEntry | None: ...


class AiCacheRepository(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def put(self, key: str, payload: str, *, player_id: UUID | None, kind: str) -> None: ...


class LlmGateway(Protocol):
    """Внешняя модель. None — нет ключа или сбой; сценарий тогда берёт заготовку."""

    enabled: bool

    async def complete(
        self,
        *,
        system: str,
        user: str,
        max_tokens: int = 160,
        temperature: float | None = None,
    ) -> str | None: ...


class ShopRepository(Protocol):
    async def list_items(self) -> list[ShopItem]: ...
    async def get_item(self, slug: str) -> ShopItem | None: ...
    async def add_purchase(self, purchase: Purchase) -> None: ...
    async def count_discount_purchases(self, player_id: UUID, week_id: UUID) -> int: ...
    async def count_discount_purchases_total(self, player_id: UUID) -> int: ...
    async def count_need_purchases(self, player_id: UUID, week_id: UUID) -> int: ...
    async def list_owned_slugs(self, player_id: UUID) -> list[str]: ...


class TaskRepository(Protocol):
    async def list_defs(self) -> list[TaskDef]: ...
    async def get_def(self, slug: str) -> TaskDef | None: ...
    async def list_questions(self, lesson_slug: str) -> list[QuizQuestion]: ...
    async def get_progress(
        self, player_id: UUID, week_id: UUID, slug: str
    ) -> TaskProgress | None: ...
    async def upsert_progress(self, progress: TaskProgress) -> None: ...
    async def count_rewarded(self, player_id: UUID) -> int: ...


class EventRepository(Protocol):
    async def list_defs(self) -> list[EventDef]: ...
    async def get_def(self, slug: str) -> EventDef | None: ...
    async def get_for_day(
        self, player_id: UUID, week_id: UUID, day: int
    ) -> EventInstance | None: ...
    async def get(self, instance_id: UUID) -> EventInstance | None: ...
    async def add(self, instance: EventInstance) -> None: ...
    async def save(self, instance: EventInstance) -> None: ...


class BadgeRepository(Protocol):
    async def list_defs(self) -> list[Badge]: ...
    async def upsert_progress(self, player_id: UUID, slug: str, percent: int) -> None: ...


class UnitOfWork(Protocol):
    """Одна транзакция на один сценарий. Коммит делает сценарий, откат — контекст."""

    players: PlayerRepository
    pets: PetRepository
    weeks: WeekRepository
    goals: GoalRepository
    log: LogRepository
    shop: ShopRepository
    tasks: TaskRepository
    events: EventRepository
    badges: BadgeRepository
    ai: AiCacheRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *exc: object) -> None: ...
    async def commit(self) -> None: ...
